### ISSUE TITLE
feat: Add config for instanceId

### ISSUE THREAD

**Issue by FLKWSKI** [Unleash/unleash-proxy#10]
Currently it is not possible do define the instanceId that unleash-proxy is using in its unleash-client.
unleash-proxy generates a random instanceId that can not be overwriten in any way.

This makes it impossible to use unleash-proxy with a GitLab Managed Unleash Instance.
GitLab uses instanceId's as a way of identifiying different users and requires you to use a specific instanceId provided by them.

It would be awesome if you could make the instanceId configurable, for example via an environment variable.

**Comment by ivarconr** [comment]
Fixed with #19
