### ISSUE TITLE
Support for refresh interval jitter

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash-proxy#108]
### Describe the feature request

Add support to configure refresh interval jitter.

### Background

Having all proxy instances send metrics at the same time can put uneven load on the server, that would much easier to handle if there was a jitter.

### Solution suggestions

Add a `refreshIntervalJitter` config option.

**Comment by Meemaw** [comment]
Actually, it seems posting metrics is the main issue. Here is a chart

<img width="1195" alt="Screenshot 2022-12-13 at 10 48 25" src="https://user-images.githubusercontent.com/8524109/207284552-cba9a566-09e5-452f-9d12-3ea12a20b173.png">

**Comment by thomasheartman** [comment]
Hey! Sorry for the long delay here 🙋 

Yeah, we agree that this sounds like a sensible thing to add. Whether it'd be better to add jitter only for the first send and then send at regular intervals thereafter or to add jitter for every request is still uncertain, but that can be discussed and decided.

Anyway, would you be willing to make a PR for this? We'd be happy to provide guidance, of course 😄

**Comment by Meemaw** [comment]
@thomasheartman this would have to be implemented in each client separately, right? For proxy in particular, that would be node client.

**Comment by guscost-opensea** [comment]
I think if we only delay on the initial metrics startup, we would only have to update the unleash-proxy package. PR above.

**Comment by thomasheartman** [comment]
@Meemaw @guscost-opensea : 

Yeah, if you only add it to the startup, then it should suffice to only update the proxy, but as you mentioned in the PR: it might make more sense to add jitter for every request. That would require updates both to the Node SDK and to the proxy.

**Comment by ivarconr** [comment]
Node SDK `v3.18.0-beta.0` introduced support for jitter on the metrics interval. 

We need to be mindful that the proxy customize the metrics sligthly ([see code](https://github.com/Unleash/unleash-proxy/blob/main/src/client.ts#L96-L107))

In addition we need to expose the same jitter option in the proxy (also as an environment variable).

**Comment by ivarconr** [comment]
Released as part of `v0.14.0-beta.0`. 

Do you mind testing it a bit @Meemaw ?

**Comment by Meemaw** [comment]
We still use fairly old version of proxy, mainly due to https://github.com/Unleash/unleash-proxy/issues/86
