### ISSUE TITLE
Proxy doesn't forward metrics received to Unleash server

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-proxy#11]
To reproduce:
1. Use https://github.com/Unleash/unleash-android-proxy-sdk
2. When configuring the client, call `enableMetrics()`
3. Run proxy locally
4. See that metrics from proxy-sdk does get registered, and `metrics.count(name: string, enabled: boolean)` does get called
5. No POST to unleash `/api/client/metrics` happens

So this bug might be in how we instantiate the metrics class, or it's a bug in the node-client-sdk.

**Comment by ivarconr** [comment]
Fyi; it is not forwarded right away, but further aggregated and posted at the send metrics interval, which defaults to 30s.

**Comment by chriswk** [comment]
I am aware, and no, there was no metrics posted at all during a 15 minute test run, otherwise I would not have made the issue :)

**Comment by chriswk** [comment]
Having tested unleash-client-node, it does report metrics, which means the bug is in the proxy code. Maybe something related to the interval timer and our custom instantiation. I'll delve deeper

**Comment by chriswk** [comment]
the `example.js` was tricking me and running with default configuration rather than what was being sent in, it was importing index, which is currently calling `start()`, I'll update the run file to actually start the way the code says it does.

**Comment by chriswk** [comment]
But I can confirm we did send metrics when I got it to load properly, so am closing this as WONTFIX

**Comment by chriswk** [comment]
Running into the same problem when starting
```bash
docker run -it --name unleash-proxy -e LOG_LEVEL=debug -e UNLEASH_URL=<url> -e UNLEASH_API_TOKEN=<token> -e UNLEASH_PROXY_SECRETS=proxy-123 -e PORT=3200 -p 3200:3200 unleashorg/unleash-proxy
```

Even though my proxy client is sending metrics, I'm not seeing a POST from proxy to unleash after waiting 2 minutes

**Comment by chriswk** [comment]
My proxy is receiving this every minute, so I would expect up to 90 seconds lag from I click and get an evaluation to seeing it in the proxy, but have now waited 5 minutes and still not a single POST
```
I/MetricsReporter: Reporting Report(appName=unleash-android, environment=dev, instanceId=unleash-android--1600581188057626275, bucket=Bucket(start=2021-07-15T08:00:09.600Z, stop=2021-07-15T08:01:09.599Z, toggles={unleash_first_fragment_demo=EvaluationCount(yes=29, no=0, variants={}), unleash_second_fragment=EvaluationCount(yes=29, no=0, variants={})}))
```

**Comment by chriswk** [comment]
Adding a log line to the proxy /client/metrics endpoint yields
```
Received metrics for unleash-android with instanceId: unleash-android--1600581188057626275, environment: dev and bucket (start: Thu Jul 15 2021 09:52:09 GMT+0200 (Central European Summer Time), stop: Thu Jul 15 2021 09:53:09 GMT+0200 (Central European Summer Time))"
```
So we are definitely getting the data to the proxy.

**Comment by chriswk** [comment]
Ah. I found the problem in unleash's logs. Metrics are indeed being sent, but since we didn't use a trailing slash on the UNLEASH_API_URL, it's getting sent to 
```
[2021-07-15T10:08:21.216] [INFO] HTTP - 404 POST /client/metrics
```
Instead of `/api/client/metrics`

So that can be fixed with a configuration setting, and since this is being done inside unleash-client-node, I guess handling non-trailing URL on the unleash-api-url should be an issue on that repo rather than here.
