### ISSUE TITLE
Connecting to gitlab ERROR: Error: Unleash Repository error: Response was not statusCode 2XX, but was 401 

### ISSUE THREAD

**Issue by icaspi** [Unleash/unleash-proxy#121]
### Describe the bug

I'm running a proxy on my local that is connected to gitlab. When  I use the code below to connect from a local express the output is Response was not statusCode 2XX, but was 401 
```ts 
try {
    const unleashProxy = createApp({
      unleashUrl: "http://localhost:3000/proxy",
      unleashApiToken: "not needed for gitlab",
      clientKeys: ["secret"],
      refreshInterval: 10000,
      logLevel: "debug",
    });
} catch (error) {
  console.error(error);
}
```

When trying to connect from postman to `http://localhost:3000/proxy` with the header `{authorization: secret}`  the response is what I expected
```json
{
    "toggles": [
        {
            "name": "logo_banner",
            "enabled": true,
            "variant": {
                "name": "disabled",
                "enabled": false
            }
        }
    ]
}

I'm assuming that the header isn't populated in the client but I'm not sure why.
```

### Subscription type

Open source

### Hosting type

None

### SDK information (language and version)

"@unleash/proxy": "^0.13.1"

**Comment by ivarconr** [comment]
Hi, 

GitLab requires instanceId and appName to be set correctly in order to connect the Unleash Proxy. 

Please read their see: https://gitlab.com/gitlab-org/gitlab/-/issues/354087 for reference.
