### ISSUE TITLE
Add option to expose metrics via prometheus endpoint

### ISSUE THREAD

**Issue by artur-fijalkowski** [Unleash/unleash-proxy#138]
Right now prometheus endpoint is not very useful for actual monitoring because it just responds with 
```
# HELP unleash_proxy_up Indication that the service is up. 
# TYPE unleash_proxy_up counter
unleash_proxy_up 1
```
But if clients send metrics, then this endpoint could expose those metrics.
This would be useful for users using feature flag providers that do not support metrics direclty (eg. gitlab feature flags).

**Comment by robmonct** [comment]
@artur-fijalkowski How you can get that metric?

**Comment by robmonct** [comment]
Thank you @evsasha

**Comment by gastonfournier** [comment]
Our recommendation here is to migrate to edge: https://github.com/Unleash/unleash-edge following this migration guide: https://github.com/Unleash/unleash-edge/blob/main/migration-guide.md
