### ISSUE TITLE
Add CurrentTime to createRequestParameters

### ISSUE THREAD

**Issue by AdrienFromToulouse** [Unleash/unleash-proxy#160]
### Describe the feature request

Hi,

Following https://github.com/Unleash/unleash-proxy-client-js/pull/195 and https://github.com/Unleash/proxy-client-react/pull/158 I think we should also have the `CurrentTime` prop available here? https://github.com/Unleash/unleash-proxy/blob/main/src/unleash-proxy.ts#L79-L84

Cheers,

**Comment by sighphyre** [comment]
Hey, thanks, good catch. This probably should be in here. I'll patch this in the next few days

Just a warning, this project is approaching end of life. We strongly recommend using [Unleash Edge](https://github.com/Unleash/unleash-edge) instead

**Comment by AdrienFromToulouse** [comment]
oh was not aware of `Unleash edge`. Thank you for the upcoming update, in the meantime we will plan a rollout out of `Unleash edge` I guess.

**Comment by sighphyre** [comment]
@AdrienFromToulouse It's not urgent to upgrade, the Proxy will be around for a long, long time. Probably at some point this year we'll formally mark this project as hitting EOL, but that will mostly just mean we won't add new features, we'll continue to do bugfixes and security updates as needed

We've released v1.1.0 of the Proxy, which should now accept current time

**Comment by AdrienFromToulouse** [comment]
> @AdrienFromToulouse It's not urgent to upgrade, the Proxy will be around for a long, long time. Probably at some point this year we'll formally mark this project as hitting EOL, but that will mostly just mean we won't add new features, we'll continue to do bugfixes and security updates as needed
> 
> We've released v1.1.0 of the Proxy, which should now accept current time

sweeeeeet. Thank you so much for the quick update ❤️ really appreciate.

**Comment by sighphyre** [comment]
Nothing but a pleasure!
