### ISSUE TITLE
Segments not working with EXP_SERVER_SIDE_SDK_CONFIG_TOKENS

### ISSUE THREAD

**Issue by rossipedia** [Unleash/unleash-proxy#201]
### Describe the bug

`/proxy/client/features` does not include segment information when requested by a client using one of the keys configured in `EXP_SERVER_SIDE_SDK_CONFIG_TOKENS`. This leads to `unleash-client-node` and `unleash-client-go` (and others I assume) to return invalid `isEnabled()` checks for features that have been assigned segments, when those clients connect to a proxy instead of an `unleash-server` instance.

### Steps to reproduce the bug

1. In your Unleash instance, create a Segment constraint
2. Create a Feature and assign that Segment to it
3. Configure `unleash-proxy` with `EXP_SERVER_SIDE_SDK_CONFIG_TOKENS`
4. Configure an `unleash-client-node` instance to connect to the proxy URL instead of an `unleash-server` `/api` URL
5. Check the feature with context that should satisfy the segment constraint.

This will return `false` for the `isEnabled()` check. 

### Expected behavior

`isEnabled()` should return `true` when passing a context that satisfies the Segment constraint.

If you connect the `unleash-client` directly to the `unleash-server` instance (using a Client API Token), then it will return `true` as expected.

### Logs, error output, etc.

```bash
I created a minimal reproduction of this issue here:

https://github.com/rossipedia/unleash-proxy-segment-bug
```

### Screenshots

<img width="854" alt="image" src="https://github.com/user-attachments/assets/75ec6a1d-c078-41ca-b1b8-69690771c4cb">

### Additional context

I traced this down to the `unleashApi` method of the `UnleashProxy` class ([here](https://github.com/Unleash/unleash-proxy/blob/7384565a13d87e0665d835f5356b999e769194fb/src/unleash-proxy.ts#L455)), which ultimately calls [`repository.getToggles()`](https://github.com/Unleash/unleash-client-node/blob/a30b59f0de782b2ae42fb6f8cae99b94e0fefe81/src/repository/index.ts#L411-L422). Even if `getTogglesWithSegmentData()` were called, that method inlines the segment constraints into the feature definitions, rather than preserving the format of the initial `/api/client/features` response, which is what a consuming client expects.

Ideally, the response from `/proxy/client/features` when served from an `unleash-proxy` instance should be identical to the one that returns from `/api/client/features` when requested from an `unleash-server` instance.

I have verified the same broken behavior exists when using `unleash-client-go`, which gives the following debug output when connecting to `unleash-proxy` using `EXP_SERVER_SIDE_SDK_CONFIG_TOKENS`:

```
ERROR: segment does not exist
```

> [!NOTE]
> `unleash-edge` does not exhibit this behavior. I believe updating `unleash-proxy` is still worthwhile though, as some consumers may not be able to easily migrate off of `unleash-proxy`.

### Unleash version

Latest

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

unleash-proxy, latest version

**Comment by FredrikOseberg** [comment]
Hi @rossipedia 

This repository is currently in maintenance mode and will not receive further development other than security patches going
forward. Unfortunately we will not continue development or fix experimental features here.

We've developed [unleash-edge](https://github.com/unleash/unleash-edge) to be the successor to the unleash-proxy, so we recommend you use edge instead to handle your traffic.
