### ISSUE TITLE
Port option not honored

### ISSUE THREAD

**Issue by PEZ** [Unleash/unleash-proxy#25]
Hello, thanks for providing!

I'm running another service at port 3000 so tried starting the proxy like so:

```sh
docker run \
   -e UNLEASH_PROXY_SECRETS=some-secret \
   -e UNLEASH_URL=https://app.unleash-hosted.com/demo/api/ \
   -e UNLEASH_API_TOKEN=56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d \
   -p 3333:3333 \
   unleashorg/unleash-proxy
```

However, it returns:

```
Unleash-proxy is listening on port 3000!
```

And it's not just the message that is wrong, I think, because:

```sh
$ curl http://0.0.0.0:3333/proxy -H "Authorization: some-secret"  

curl: (52) Empty reply from server
```

Whereas if I start with `-p 3000:3000` I get some nice flag config back.

**Comment by ivarconr** [comment]
Hi there, you need to inform the proxy on which PORT you want it to listen on.

Try:

```sh
docker run \
   -e UNLEASH_PROXY_SECRETS=some-secret \
   -e UNLEASH_URL=https://app.unleash-hosted.com/demo/api/ \
   -e UNLEASH_API_TOKEN=56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d \
   -e PORT=3333
   -p 3333:3333 \
   unleashorg/unleash-proxy
```

**Comment by ivarconr** [comment]
I see however that we have failed to add "PORT" to the list of possible options you can specify. So to resolve this issue we should fix that!

**Comment by PEZ** [comment]
Thanks for the quickest help ever!

I am a Docker noob, so didn't realize the option was for docker 🤦 .

If I start it with `-p 3333:3000` I can actually rely on the 3000 default.

I can add PORT to the list by PR, if you haven't already.

**Comment by ivarconr** [comment]
> I can add PORT to the list by PR, if you haven't already.

please do 👍🏼
