### ISSUE TITLE
fix: Improve loading of custom strategies in docker. 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-proxy#29]
In order to successfully load custom strategies inside docker you will currently need to also bundle the unleash-client dependency, like this:

```bash
npm init -y
npm install unleash-client
```

Now you should be able to load a custom strategy like this in docker:

```sh
docker run \
   -e UNLEASH_PROXY_SECRETS=some-secret \
   -e UNLEASH_URL=https://app.unleash-hosted.com/demo/api/ \
   -e UNLEASH_API_TOKEN=56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d \
   -e UNLEASH_CUSTOM_STRATEGIES_FILE=/config/toggle-strategies.js \
   --mount type=bind,source="$(pwd)"/config,target=/config \
   -p 3333:3000 \
   unleashorg/unleash-proxy
```

And in the local directory in `./config/toggle-strategies.js` I have:

```javascript
const unleash = require('unleash-client');

class WorkspaceStrategy extends unleash.Strategy {
  constructor() {
    super('fy-workspace');
  }

  isEnabled(parameters, context) {
    return parameters['fy-workspace-id'].includes(context['fy-workspace-id']);
  }
}

module.exports = [new WorkspaceStrategy()];
```

 We should not require the user to also add the unleash-client dependency because we already have this inside the proxy. We need to find a way to reuse the loaded dependency when loading these custom strategy implementations from a mounted folder.

**Comment by jonasws** [comment]
I was able to achieve this by copying the strategy into `./dist` in our `Dockerfile`:
```Dockerfile
FROM unleashorg/unleash-proxy:0.7.0

COPY groups-strategy.js /unleash-proxy/dist

ENV UNLEASH_CUSTOM_STRATEGIES_FILE ./groups-strategy.js
```
I'm guessing one could change the "startup" command of the proxy to be "aware" of `UNLEASH_CUSTOM_STRATEGIES_FILE` and copy it into the correct folder on startup?

**Comment by ivarconr** [comment]
Thanks for sharing @jonasws, this does sound like an improvement we should look in to.
