### ISSUE TITLE
Question: What's the license?

### ISSUE THREAD

**Issue by TrueWill** [Unleash/unleash-proxy#33]
What license is the proxy released under?

Also please consider adding a LICENSE file. Thank you!

**Comment by ivarconr** [comment]
This is a slipup from our side when open-sourcing the proxy in June. We removed the closed-source license, but forgot to add a new one. For now the npm module has been published with a ICS license ([package.json](https://github.com/Unleash/unleash-proxy/blob/main/package.json#L27)), so I guess that kind of applies.

I actually assume we are going to switch to Apache 2.0 (as we currently use for most of our products), but need to check that internally first.
