### ISSUE TITLE
Feature: Allow Turning a Feature On/Off from Context Perspective

### ISSUE THREAD

**Issue by EmadBinAbid** [Unleash/unleash-proxy#35]
As of now, `unleash-proxy` is a suitable solution for one of my use cases i.e. fetch enabled features for a context. Let's say I have a context property (constraint) of `location` on features `A`, `B`, and `C`. With `unleash-proxy` in place, I can easily find if `A`, `B`, and `C` are enabled on location, say `X`. 

Extending to it, I have another use case where I want to be able to enable/disable a feature for a particular context (constraint). For instance, ideally, given a feature `name` and constraint's `contextName` and value, I want an API that would internally fetch that feature by `name`, iterate over all of its `strategies`, and for each strategy, iterate over all the `constraints`, and then finally add the value to the list of `values` of that constraint. 

Right now, I am handling all of this logic on my end using the following steps:

1. Get feature by name (`unleash-server` API call)
2. Iterate over `strategies` and `constraints` of the fetched feature object, updating the payload, and then updating the feature (`unleash-server` API call).

Ideally, these responsibilities should not be on consumer's end because the logic is a bit complex and involves two network requests.

**Comment by thomasheartman** [comment]
Hey, @EmadBinAbid ! First off: sorry, it appears this entirely slipped between the cracks 🙇🏼 

Now, let's turn to your feature request. Is what you're asking for _a way to dynamically add constraints_ at runtime from the Proxy? I'm not entirely sure I understand. Could you give me a concrete example? They're often easier for getting specific use cases. Thanks! 😄
