### ISSUE TITLE
Authorize users based on JWT token

### ISSUE THREAD

**Issue by SimonSimCity** [Unleash/unleash-proxy#36]
Provide a list of specific JWT token provider instead of a shared secret.

In my example, I'm building a single page application using Azure B2C as the user base. I envision that I can give this package some kind of public version of telling that it should accept all valid tokens from my JWT token provider. This would make this proxy more secure by not relying on having a shared secret with the website.

**Comment by ivarconr** [comment]
Hi @SimonSimCity, 

interesting suggestion. It would be good if you could outline a bit more details on how you envision this should work. 

fyi;
You can always depend on the proxy as a npm module, and add any custom middleware in front to do whatever you need.
