### ISSUE TITLE
fix: Add config for CORS header

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-proxy#4]
today we have a default for CORS. It could be good if the customers was allowed to configure their custom CORS header when needed.

**Comment by lewisloofis** [comment]
Hi, how's this issue going? our app use unleash proxy and meet CORS error, so I think we need this

**Comment by ivarconr** [comment]
We should add a few options to control the essential parts, like providing a list of `origins` and `maxAge`
https://expressjs.com/en/resources/middleware/cors.html

Any takers?
