### ISSUE TITLE
Cannot connect to local unleash server

### ISSUE THREAD

**Issue by rodrigofazenda** [Unleash/unleash-proxy#40]
Hello,

I'm trying to set up a local unleash server with the unleash proxy. However, I'm facing this error when running unleash-proxy:
`ERROR: FetchError: Unleash Repository error: request to http://localhost:4242/api/client/features failed, reason: connect ECONNREFUSED 127.0.0.1:4242`

I started the unleash-docker following these instructions: https://github.com/Unleash/unleash-docker#work-locally-with-this-repo

And I'm running unleash-proxy with this:
`docker run -e UNLEASH_PROXY_SECRETS=some-secret -e UNLEASH_URL=http://localhost:4242/api/ -e UNLEASH_API_TOKEN="*:development.03b484052e9244c40ec4080216c4f00fcb3ef5e2c995a4468814e3bf" -p 3000:3000 unleashorg/unleash-proxy`

How can I troubleshoot this error?

Thanks in advance.

**Comment by ivarconr** [comment]
for the proxy you need to be on the same network as unleash. try add "--network unleash" to the docker run command.

**Comment by ivarconr** [comment]
also, you need to give unleash-server a name via `--name unleash` and then the url to the unleash API will be `UNLEASH_URL=http://unleash:4242/api/ `

**Comment by rodrigofazenda** [comment]
Thanks @ivarconr 

Docker-compose creates a default network called `unleash-docker_default`. Adding `--network unleash-docker_default` and changing the URL from localhost to unleash worked.
