### ISSUE TITLE
Your documentation is ahead of docker hub image versions!

### ISSUE THREAD

**Issue by theMasix** [Unleash/unleash-proxy#42]
`README.md` has a `UNLEASH_CLIENT_KEYS` option which is supposed to become supported since version 0.5. But the docker hub latest image version is 0.4.0. So the documentation is ahead of the docker hub image version.

**Comment by ivarconr** [comment]
Thanks for letting us know. There was a missing tag for that release, which affected the actions that performs the actual release.
