### ISSUE TITLE
ERROR: Error: Unleash Repository error: Response was not statusCode 2XX, but was 401

### ISSUE THREAD

**Issue by dmzoneill** [Unleash/unleash-proxy#45]
Hi

I deployed unleash and postgress as described here:
https://hub.docker.com/r/unleashorg/unleash-server

I logged into unleash using 'admin' and 'unleash4all'.
i created an api token as admin.

i then ran unleash-proxy as documented using the token.

```
docker run    -e UNLEASH_PROXY_SECRETS=some-secret    -e UNLEASH_URL=http://192.168.122.195:4242/api/    -e UNLEASH_API_TOKEN=728934fd84bb7926ecd5367602fe5efc3550c66778b210d978576254    -p 3000:3000    unleashorg/unleash-proxy
Unleash-proxy is listening on port 3000!
ERROR: Error: Unleash Repository error: Response was not statusCode 2XX, but was 401 
ERROR: Error: Unleash Repository error: Response was not statusCode 2XX, but was 401 
```

hitting the interface http://192.168.122.195:4242/api/ returns

{"type":"password","path":"/auth/simple/login","message":"You must sign in order to use Unleash","defaultHidden":false}

**Comment by ivarconr** [comment]
The error message tells you that the Unleash Proxy was not able to connect to the Unleash API, the API key was not accepted (thus a 401)

The API token looks a bit strange as it follows the old syntax. Which version of unleash-server are you running?

Can you please validate the api enpoint with a simple curl command:

```sh
curl http://192.168.122.195:4242/api/client/features  -H "Authorization: 728934fd84bb7926ecd5367602fe5efc3550c66778b210d978576254"
```

**Comment by dmzoneill** [comment]
hey thanks,

i dropped the extra stuff at the start of the token.  i presumed it was superfluous.  
The format as you said, was the older format?  adding in the '*.*.' before the token has resolved it.

docker run    -e UNLEASH_PROXY_SECRETS=some-secret    -e UNLEASH_URL=http://192.168.122.195:4242/api/    -e UNLEASH_API_TOKEN=*:*.6f5282f4683ff2c3c628db0fe629312e273a92fecf49c824ae4c092e    -p 3000:3000    unleashorg/unleash-proxy
Unleash-proxy is listening on port 3000!

working now
curl http://192.168.122.195:4242/api/client/features  -H "Authorization: *:*.6f5282f4683ff2c3c628db0fe629312e273a92fecf49c824ae4c092e"
{"version":2,"features":[],"query":null}
