### ISSUE TITLE
Wait for the proxy to be ready to receive traffic

### ISSUE THREAD

**Issue by MaryBagratunyan** [Unleash/unleash-proxy#46]
We are trying to deploy unleash proxy with AWS Lambda.

The example of handler function is the following

```
import { createApp } from '@unleash/proxy';
import * as serverless from 'serverless-http';

export const proxyHandler = async (event, context) => {
  const app = createApp({
    unleashUrl: process.env.UNLEASH_URL,
    unleashApiToken: process.env.UNLEASH_API_TOKEN,
    clientKeys: ['some-secret'],
    refreshInterval: 1000,
  });

  const handler = serverless(app);

  return handler(event, context);
};
```

The problem is that we should wait for the 'ready' event to be triggered before ‘wrapping’ the app for serverless use.

I have seen an approach in library's examples when passing a client as a second argument to the createApp function and making client.emit('ready') after, but the Client class is not exported by the library so this is not possible for us.

Please, can you help me with an answer whether there's a good solution to wait for/check the proxy to be ready to receive traffic.

**Comment by ivarconr** [comment]
This is interesting question. I think we should try to add something, but I am unsure if you can do that via the returned express app instance. We should probably return something more. 

..But, you can actually pass a custom unleash client instance, and the proxy will use that instead of creating its own instance, and then you will have direct access to all internal SDK events.

**Comment by ivarconr** [comment]
@MaryBagratunyan is your code publicly available somewhere, would be nice to see the end result as a lambda!

**Comment by MaryBagratunyan** [comment]
> This is interesting question. I think we should try to add something, but I am unsure if you can do that via the returned express app instance. We should probably return something more.
> 
> ..But, you can actually pass a custom unleash client instance, and the proxy will use that instead of creating its own instance, and then you will have direct access to all internal SDK events.

If I'm not missing anything in order to create custom client to pass, compatible with type Client, I have to implement the class Client from client.js myself and the config.js and logger.js too, so basically I have to copy the three files from library, am I right?

I see the following quick solutions
1. Export the Client and createProxyConfig from config.js as well in order to let the user create custom client and pass it.
2. Emit the 'ready' with the app too, so the user will be able to listen.

What do you think about the solutions? I can implement them and create a PR if you're okay with that

**Comment by MaryBagratunyan** [comment]
> @MaryBagratunyan is your code publicly available somewhere, would be nice to see the end result as a lambda!

Sure, I can post the code here when it'll be ready

**Comment by MaryBagratunyan** [comment]
@ivarconr you can find a simple codebase for deploying unleash proxy with aws lambda here https://github.com/MaryBagratunyan/unleash-proxy-lambda

**Comment by slawekkolodziej** [comment]
For what it's worth, I also managed to deploy unleash-proxy to serverless app with [@vendia/serverless-express](https://www.npmjs.com/package/@vendia/serverless-express). My setup code was almost identical to what is described in the 'Async setup Lambda handler' section.
