### ISSUE TITLE
Using proxy and proxy client in the same process

### ISSUE THREAD

**Issue by azazdeaz** [Unleash/unleash-proxy#47]
When i run the `unleash-proxy` in a nodejs process where i also want to read toggle states, how should i query them? 
I see that there is an option to replace fetch in `unleash-proxy-client-js` but is it prossible to query the proxy without making an extra http request? 
I see the second argument of `createApp()` is `client`, but it's not documented yet. Would it be safe to use that?

Also, thanks a lot for this great tool! :heart:

**Comment by azazdeaz** [comment]
This is my current solution. Is this a safe/sane way to use the client?

```js
import { createApp } from '@unleash/proxy';
import Client from '@unleash/proxy/dist/client';
import { createProxyConfig } from '@unleash/proxy/dist/config';

const config = {
  //...
};

const client = new Client(createProxyConfig(config));

const waitReadyPromise = new Promise((resolve) => {
  client.on('ready', () => resolve());
});

export const unleashProxyApp = createApp(config, client);

export const isToggleOn = async (toggleName, userId) => {
  await waitReadyPromise;
  const context = { userId };
  return client
    .getEnabledToggles(context)
    .some((toggle) => toggle.name === toggleName && toggle.enabled);
};
```

**Comment by ivarconr** [comment]
This would work just fine. The only thing you should be aware of is if you want to stop the unleash client, it will cause the proxy to come in a weird state.
