### ISSUE TITLE
Types declarations missing in package

### ISSUE THREAD

**Issue by christian98** [Unleash/unleash-proxy#53]
When i try to install the `@unleash/proxy` package into an Typescript project. My compiler is complaining that there are no type definitions for this package. 
```
TS7016: Could not find a declaration file for module '@unleash/proxy'. '/path-to-project/node_modules/@unleash/proxy/dist/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/unleash__proxy` if it exists or add a new declaration (.d.ts) file containing `declare module '@unleash/proxy';`
```
When i look into the package in my `node_modules` folder i can confirm, that there are no `.d.ts` files.
Defining the module by myself like this:
```typescript
declare module '@unleash/proxy' {
    export * from '@unleash/proxy';
}
```
only leads to an error saying that there are no types for package `compression` (a dependency of `@unleash/proxy`)
As this is not my direct dependency, i actually dont want to install the types for this..

Would it be possible to publish theses types within the package? This would make it alot easier to use it with typescript.

**Comment by ivarconr** [comment]
Make sense. Feel free to open a PR.
