### ISSUE TITLE
CORS Configuration does not apply for 304 refresh requests

### ISSUE THREAD

**Issue by sheastyer** [Unleash/unleash-proxy#82]
### Describe the bug

Configured our proxy server with the following
```
cors: {
        origin: 'http://localhost:3000'
    }
```

When making the initial request on page load for the flags, we get a perfect 200 with the header
```
Access-Control-Allow-Origin: http://localhost:3001
```
as expected, browser is happy. 

Now, on a refresh request 30 seconds later (determined by `refreshInterval`) the same request is made with an extra header, something like 
```
if-none-match: W/"101-w8M2PbyIXvu4DpZVMs3eAhoAXXU"
```
which I assume is just meant to save on compute by looking at a cache id. No problems

But the response we get (with a 304 as expected) does **not** have the CORS header like the original response has
```
Access-Control-Allow-Origin: http://localhost:3001
```
In fact, it has no CORS headers at all. This makes the browser unhappy and we end up with a failure every time it tries to refresh. 

### Steps to reproduce the bug

1. Set the cors origins to be some value on the proxy server
2. Make a request with Postman to get the toggles using a client id
3. Note that the CORS origin you specified is set in the response header: `Access-Control-Allow-Origin`
4. Take the `ETag` header from that response, and stick it in the request headers with the key `if-none-match`
5. Make the request again, which should be a status code 304. 
6. Evaluate the headers, and notice the same CORS header is not included in the second response.  Access-Control-Allow-Origin

### Expected behavior

Expected behavior should be to still respond with a 304 HTTP code, but the requested CORS config should also be put on the response from the proxy server. 

### Unleash version

latest

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by nya1** [comment]
Hello,
Are you able to provide the error that you receive on the browser?
I tried to reproduce the issue locally following the mentioned steps but I'm always getting back the `Access-Control-Allow-Origin` header, examples requests made with curl (I also tested via an html page and getting the same behavior):

```
❯ curl -I --location --request GET 'http://localhost:3000/proxy?userId=99' \
-H 'Origin: http://example.com' \
-H 'Authorization: some-secret'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://example.com
Vary: Origin, Accept-Encoding
Cache-control: public, max-age=2
Content-Type: application/json; charset=utf-8
Content-Length: 9299
ETag: W/"2453-1yoqHWPP3DU/zVKAUXQQ02ygZQ0"
Date: Fri, 15 Jul 2022 11:50:48 GMT
Connection: keep-alive
Keep-Alive: timeout=5

❯ curl -I --location --request GET 'http://localhost:3000/proxy?userId=99' \
-H 'Origin: http://example.com' \
-H 'Authorization: some-secret' \
-H 'if-none-match: W/"2453-1yoqHWPP3DU/zVKAUXQQ02ygZQ0"'
HTTP/1.1 304 Not Modified
Access-Control-Allow-Origin: http://example.com
Vary: Origin
Cache-control: public, max-age=2
ETag: W/"2453-1yoqHWPP3DU/zVKAUXQQ02ygZQ0"
Date: Fri, 15 Jul 2022 11:50:52 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
Cors options used: (tested also using localhost)
```
    cors: {
        origin: 'http://example.com',
    }
```

p.s. probably it's a typo but the `Access-Control-Allow-Origin` response header that you receive should be the same as the one that you have entered during cors initialization (the same location where your webapp is located), so in your case should return `http://localhost:3000` and not `http://localhost:3001`

**Comment by sheastyer** [comment]
Turns out, I was unable to repro this when connecting directly to the proxy. I am not too worried, the whole point of the reverse proxy is to get all requests to be same-origin when hosted, so this won't be an issue besides local dev. And we can use a non-reverse-proxied unleash proxy there. Thanks for the help @nya1!
