### ISSUE TITLE
Disable prometheus endpoint

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash-proxy#86]
### Describe the bug

Is it possible to add configuration option to disable prometheus endpoints, like one the unleash API server? This can potentially expose sensitive underlying host information.

Endpoint added in https://github.com/Unleash/unleash-proxy/pull/78

**Comment by andreas-unleash** [comment]
Thanks! I will bring to the attention of the team and get back to you as soon as possible

**Comment by andreas-unleash** [comment]
Hi @Meemaw ,  this is definitely something we want to do someday, but unfortunately cannot say when.  We would be happy to review a PR if you send us one, otherwise we will get to it as soon as possible.
