### ISSUE TITLE
Allow configuring the value for  httpOptions.rejectUnauthorized via Environment variables

### ISSUE THREAD

**Issue by vkbandi** [Unleash/unleash-proxy#99]
When using unleash proxy docker image, it is not possible to configure it to allow self signed certificates, I have tried using the environment variables `NODE_EXTRA_CA_CERTS `and `NODE_TLS_REJECT_UNAUTHORIZED`, both doesn't appear to stop the "request to https://gitlab.example.com/api/v4/feature_flags/unleash/000000/client/register failed, reason: self signed certificate in certificate chain" error.

The only workaround is to run the unleash proxy as a node js application and adding `httpOptions: { rejectUnauthorized: false }` in the createApp configuration

### Example

```
const app = createApp({
    unleashUrl: 'https://gitlab.example.com/api/v4/feature_flags/unleash/000000',
    unleashInstanceId: '0xx-0x0_xxXXXXX0_xx0',
    unleashApiToken: 'xxxxx-xxxxxxxxxxxxxxxxxx',
    unleashAppName: "example",
    clientKeys: ['some-secret'],
    proxyPort: 3000,
    **httpOptions: { rejectUnauthorized: false }**
});
```

If the value for httpOptions.rejectUnauthorized can be read from the Environment variables, then we can use the unleash proxy with the provided docker image

**Comment by nunogois** [comment]
Hi @vkbandi - Thanks for opening this issue! I'll reach out to the rest of the team and we'll get back to you 👍

**Comment by ivarconr** [comment]
Hi, I all node.js applications you can allow any self-signed certificates by setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` (see [official node.js docs](NODE_TLS_REJECT_UNAUTHORIZED)).

How you would do this with docker then would be:

```sh
docker run \
   -e NODE_TLS_REJECT_UNAUTHORIZED=0 \
   -e UNLEASH_PROXY_CLIENT_KEYS=some-secret \
   -e UNLEASH_URL=https://app.unleash-hosted.com/demo/api/ \
   -e UNLEASH_API_TOKEN=56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d \
   -p 3000:3000 \
   unleashorg/unleash-proxy
```

**Comment by ivarconr** [comment]
I see. Maybe we need to support that as a configurable option then. Do you mind looking in to a PR?

**Comment by vkbandi** [comment]
Sorry for the late reply, let me try to create a PR

**Comment by vkbandi** [comment]
Sorry for the delay, need few more days to work on this
